[tool.poetry]
name = "listparser"
version = "0.19"
description = "Parse OPML subscription lists"
authors = ["Kurt McKee <contactme@kurtmckee.org>"]
license = "MIT"
readme = "README.rst"
repository = "https://github.com/kurtmckee/listparser/"
documentation = "https://listparser.readthedocs.io/en/latest/"
keywords = ["opml", "foaf", "igoogle", "feed"]
classifiers = [
    "Development Status :: 5 - Production/Stable",
    "Intended Audience :: Developers",
    "Topic :: Text Processing :: Markup :: XML",
]

[tool.poetry.dependencies]
python = "^3.7"
requests = {version = "^2.25.1", optional = true}
lxml = {version = "^4.6.2", optional = true}


[tool.poetry.extras]
http = ['requests']
lxml = ['lxml']


[tool.poetry.dev-dependencies]
tox = "^3.25.0"
Sphinx = "^5.0.0"
scriv = "^0.15.0"
black = "^22.3.0"
isort = "^5.10.1"
pre-commit = "^2.19.0"


[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"



[tool.coverage.run]
branch = true


[tool.coverage.paths]
source = [
    "src",
    ".tox/*/site-packages",
]


[tool.scriv]
version = "literal: pyproject.toml: tool.poetry.version"
categories = ["Added", "Fixed", "Removed", "Changed", "Deprecated", "Security"]
entry_title_template = "{{ version }} - {{ date.strftime('%Y-%m-%d') }}"
format = "rst"
fragment_directory = "changelog.d"
insert_marker = "scriv-insert-here"
main_branches = ["develop", "master"]
new_fragment_template = "file: fragment-template.rst.txt"


[tool.isort]
profile = "black"
