[tool.poetry]
name = "listparser"
version = "0.18"
description = "Parse OPML subscription lists"
authors = ["Kurt McKee <contactme@kurtmckee.org>"]
license = "LGPLv3"
readme = "README.rst"
repository = "https://github.com/kurtmckee/listparser/"
documentation = "https://listparser.readthedocs.io/en/stable/"
keywords = ["opml", "foaf", "igoogle", "feed"]
classifiers = [
    "Development Status :: 5 - Production/Stable",
    "Intended Audience :: Developers",
    "Topic :: Text Processing :: Markup :: XML",
]

[tool.poetry.dependencies]
python = "^3.6"
requests = {version = "^2.25.1", optional = true}


[tool.poetry.extras]
http = ['requests']


[tool.poetry.dev-dependencies]
tox = "^3.21.4"
Sphinx = "^3.4.3"
scriv = "^0.10.0"


[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"


[tool.tox]
legacy_tox_ini = """

[tox]
envlist =
    py{39, 38, 37, 36, py3}-{,requests}
    flake8
    docs

skip_missing_interpreters = True
isolated_build = True

[testenv]
deps =
    requests: requests
    pytest
    pytest-cov

commands =
    {envpython} -m pytest --cov --cov-append --cov-report=html lptest.py

[testenv:flake8]
deps =
    pytest
    pytest-flake8

commands =
    {envpython} -m pytest --flake8

[testenv:docs]
deps =
    sphinx

commands =
    {envpython} -m sphinx -aWEqb html docs/ build/trash

"""


[tool.coverage.run]
branch = true
source = ["listparser", "lptest.py"]


[tool.scriv]
version = "literal: src/listparser/__init__.py: __version__"
categories = ["Added", "Fixed", "Removed", "Changed", "Deprecated", "Security"]
entry_title_template = "{{ version }} - {{ date.strftime('%Y-%m-%d') }}"
format = "rst"
fragment_directory = "changelog.d"
insert_marker = "scriv-insert-here"
main_branches = ["develop", "master"]
new_fragment_template = "file: fragment-template.rst.txt"
